<a href="https://colab.research.google.com/github/gnitnaw/Programs/blob/master/Appendices/Linear%20Algebra/svdexample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version

Python 3.7.12


# Example A.9
## Import modules

In [2]:
import numpy as np
from numpy import diag, zeros,vstack
from numpy.random import rand, seed
from numpy.linalg import svd, pinv
import matplotlib.pyplot as plt
print(np.__version__)

1.19.5


## Set random seed

In [3]:
seed(12345)

## Original Program

In [4]:
n = 5
p = 8
X = rand(n,p)
print(X)
y = rand(n,1)
print(y)
U,S,VT = svd(X)  
print(U)
print(S)
print(VT)
SI  = diag(1/S)
# compute pseudo inverse
pseudo_inv = VT.T @ vstack((SI, zeros((p-n,n)))) @ U.T
b = pseudo_inv @ y
#b = pinv(X) @ y   #remove comment to use the built-in pseudo inverse
print(X @ b - y)


[[0.92961609 0.31637555 0.18391881 0.20456028 0.56772503 0.5955447
  0.96451452 0.6531771 ]
 [0.74890664 0.65356987 0.74771481 0.96130674 0.0083883  0.10644438
  0.29870371 0.65641118]
 [0.80981255 0.87217591 0.9646476  0.72368535 0.64247533 0.71745362
  0.46759901 0.32558468]
 [0.43964461 0.72968908 0.99401459 0.67687371 0.79082252 0.17091426
  0.02684928 0.80037024]
 [0.90372254 0.02467621 0.49174732 0.52625517 0.59636601 0.05195755
  0.89508953 0.72826618]]
[[0.81835001]
 [0.50022275]
 [0.81018941]
 [0.09596853]
 [0.21895004]]
[[-0.40775761 -0.63934792  0.28892349 -0.04952761 -0.58226987]
 [-0.42479179  0.30247488 -0.53342395 -0.61858731 -0.24671748]
 [-0.51975634  0.21127923  0.62879581 -0.26817582  0.46681045]
 [-0.45423002  0.48417748 -0.03062265  0.68971412 -0.28740902]
 [-0.42049269 -0.46976211 -0.48544844  0.25937026  0.54733567]]
[3.72798005 1.28541524 0.78054038 0.65448998 0.32501497]
[[-0.4554212  -0.32236693 -0.4163881  -0.37463963 -0.31624927 -0.20398119
  -0.30895737 -0.